CPUS="1"
MEMORY="1024"

Vagrant.configure("2") do |config|
  config.vm.define :puppetclient1 do |puppetclient1|
    puppetclient1.vm.box = "roboxes/centos8s"
    puppetclient1.vm.provider :libvirt do |domain|
          domain.memory = MEMORY
          domain.cpus = CPUS
    end
  end

end
