CPUS="1"
MEMORY="1024"

Vagrant.configure("2") do |config|
  config.vm.define :puppetclient1 do |puppetclient1|
    puppetclient1.vm.box = "roboxes/centos8s"
    puppetclient1.vm.provider :libvirt do |domain|
          domain.memory = MEMORY
          domain.cpus = CPUS
    end
  end
  config.vm.hostname = "puppetclient1"
  config.vm.provision "shell", inline: <<-SHELL
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
  sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  systemctl restart sshd
  yum install -y nfs-utils
  mkdir /shared
  mount -t nfs 192.168.122.1:/home/shared /shared
  echo "" >> /etc/fstab
  echo "192.168.122.1:/home/shared /shared nfs defaults 0  0" >> /etc/fstab
  echo "$(hostname -I)  $(hostname) $(hostname).local" > /shared/puppetclient1.host
  yum -y localinstall https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
  yum -y localinstall https://yum.puppetlabs.com/puppet-tools-release-el-8.noarch.rpm
  yum install -y puppet
  systemctl enable puppet
  systemctl start puppet
  SHELL

end
